version: 3.8;

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - cosmicpython-postgres:/var/lib/postgresql
    ports:
      - 5432:5432


volumes:
  cosmicpython-postgres:
