"""Create outbox model

Revision ID: 07f4dff13545
Revises: 36d489590f68
Create Date: 2025-10-04 14:54:24.090884

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "07f4dff13545"
down_revision: Union[str, None] = "36d489590f68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
