"""Make all not nullable

Revision ID: 27e5856f13a2
Revises: 4abd7c52d8cf
Create Date: 2025-10-11 18:09:50.681690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e5856f13a2'
down_revision: Union[str, None] = '4abd7c52d8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_view_model', ['order_line_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_view_model', type_='unique')
    # ### end Alembic commands ###
