"""Create order read model

Revision ID: 298b6aa88bb1
Revises: c250bf67bf7e
Create Date: 2025-10-04 17:33:01.572055

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "298b6aa88bb1"
down_revision: Union[str, None] = "c250bf67bf7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
