"""Create outbox model

Revision ID: 36d489590f68
Revises: 33416e340a44
Create Date: 2025-10-04 14:30:05.031573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36d489590f68"
down_revision: Union[str, None] = "33416e340a44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "outbox",
        "aggregate_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "outbox",
        "aggregate_id",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
