"""Create order read model

Revision ID: 4abd7c52d8cf
Revises: 298b6aa88bb1
Create Date: 2025-10-04 19:56:58.932127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4abd7c52d8cf"
down_revision: Union[str, None] = "298b6aa88bb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_view_model", "product_qty", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_view_model", "product_qty", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
