"""Create outbox model

Revision ID: ae142dca3487
Revises: 07f4dff13545
Create Date: 2025-10-04 15:10:29.540048

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ae142dca3487"
down_revision: Union[str, None] = "07f4dff13545"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
