"""Create order read model

Revision ID: c250bf67bf7e
Revises: 5acf7bd858af
Create Date: 2025-10-04 17:08:35.913370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c250bf67bf7e"
down_revision: Union[str, None] = "5acf7bd858af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_view_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("order_status", sa.String(length=255), nullable=True),
        sa.Column("order_line_id", sa.Integer(), nullable=True),
        sa.Column("product_sku", sa.String(length=255), nullable=True),
        sa.Column("product_qty", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("order", sa.Column("status", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "status")
    op.drop_table("order_view_model")
    # ### end Alembic commands ###
