"""cqsp

Revision ID: ca0315cd993b
Revises: eb38d551d6cc
Create Date: 2025-09-27 11:11:23.534769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca0315cd993b"
down_revision: Union[str, None] = "eb38d551d6cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "order_lines",
        "order_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="order_id::integer",
    )
    op.create_foreign_key(None, "order_lines", "order", ["order_id"], ["id"])
    op.create_foreign_key(None, "order_lines", "product", ["sku"], ["sku"])

    op.add_column("product", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column(
        "product", sa.Column("unit_of_measure", sa.String(length=50), nullable=True)
    )
    op.add_column("product", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.execute("UPDATE product SET name = 'UNKNOWN' WHERE name IS NULL")
    op.execute(
        "UPDATE product SET unit_of_measure = 'EACH' WHERE unit_of_measure IS NULL"
    )
    op.alter_column("product", "name", existing_type=sa.String(255), nullable=False)
    op.alter_column(
        "product", "unit_of_measure", existing_type=sa.String(50), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "is_active")
    op.drop_column("product", "unit_of_measure")
    op.drop_column("product", "name")
    op.drop_constraint(None, "order_lines", type_="foreignkey")
    op.drop_constraint(None, "order_lines", type_="foreignkey")
    op.alter_column(
        "order_lines",
        "order_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_table("order")
    # ### end Alembic commands ###
