"""add_product_defaults

Revision ID: d20d049c31a3
Revises: ce5eef437e95
Create Date: 2025-07-26 21:01:06.067391

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d20d049c31a3"
down_revision: Union[str, None] = "ce5eef437e95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
