"""Make all not nullable

Revision ID: e7fe138173c6
Revises: 27e5856f13a2
Create Date: 2025-10-11 18:10:45.975685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fe138173c6'
down_revision: Union[str, None] = '27e5856f13a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_view_model', 'order_line_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_view_model', 'product_sku',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('order_view_model', 'product_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_view_model', 'product_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_view_model', 'product_sku',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('order_view_model', 'order_line_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
