"""initial migration

Revision ID: ef873be591af
Revises:
Create Date: 2025-07-25 21:29:58.774283

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ef873be591af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
