"""create products, order_lines, batches, allocations

Revision ID: 2c7601e6a157
Revises:
Create Date: 2025-06-10 23:55:53.295110

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2c7601e6a157"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "allocations", ["orderline_id"])
    op.create_unique_constraint(None, "batches", ["reference"])
    op.create_unique_constraint(None, "products", ["sku"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    op.drop_constraint(None, "batches", type_="unique")
    op.drop_constraint(None, "allocations", type_="unique")
    # ### end Alembic commands ###
